name:                haskell-system-F
version:             0.1.0.0
github:              "githubuser/haskell-system-F"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-system-F#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck
- clock
- parsec
- statistics
- random
- deepseq
- mtl
- MonadRandom
- async
- logict
- criterion
- universe-base
- microtimer


library:
  source-dirs: src

executables:
  haskell-system-F-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-system-F

tests:
  haskell-system-F-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-system-F
